version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: corpus-client
    targets: [go_first_class]
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd/cli
    binary: corpus-client
    flags:
      - -trimpath
    ldflags:
      - -w -s -X 'github.com/bornholm/corpus/internal/build.ShortVersion={{ .Version }}' -X 'github.com/bornholm/corpus/internal/build.LongVersion={{ .Version }}'
  - id: corpus-server
    targets: [go_first_class]
    mod_timestamp: "{{ .CommitTimestamp }}"
    dir: ./cmd/corpus
    binary: corpus-server
    flags:
      - -trimpath
    ldflags:
      - -w -s -X 'github.com/bornholm/corpus/internal/build.ShortVersion={{ .Version }}' -X 'github.com/bornholm/corpus/internal/build.LongVersion={{ .Version }}'
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  name_template: "v{{ .Version }}"

dockers:
  - id: corpus-server
    ids:
      - corpus-server
    use: docker
    dockerfile: misc/docker/corpus-server.Dockerfile
    image_templates:
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/corpus-server:{{ .Version }}
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/corpus-server:latest
  - id: corpus-client
    ids:
      - corpus-client
    use: docker
    dockerfile: misc/docker/corpus-client.Dockerfile
    image_templates:
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/corpus-client:{{ .Version }}
      - ghcr.io/{{ tolower ( .Env.REPO_OWNER ) }}/corpus-client:latest
