openapi: 3.1.1
info:
  title: Corpus API
  version: 1.0.12
servers:
  - url: /api/v1
paths:
  /index:
    post:
      summary: Index a document
      operationId: index
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                source:
                  type: string
                  format: url
                  description: The URI associated to the file
                  default: ""
                collection:
                  type: string
                  description: The name of a collection to assign the document to (will be created automatically)
                etag:
                  type: string
                  description: An ETag value to associate to the current document version
                  allowEmptyValue: true
                file:
                  type: string
                  description: The file to index
                  format: binary
              required: ["file", "source", "collection"]
      responses:
        "200":
          description: Successful operation
        "400":
          description: Request invalid or malformed
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /search:
    get:
      summary: Search documents
      operationId: search
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: The search query
          required: true
        - in: query
          name: collection
          schema:
            type: array
            item:
              type: string
            allowEmptyValue: true
          description: Restrict the search to these collections
        - in: query
          name: size
          schema:
            type: integer
            min: 0
            allowEmptyValue: true
          description: Limit the number of results returned (default 3)
      responses:
        "200":
          description: Successful operation
        "400":
          description: Request invalid or malformed
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /ask:
    get:
      summary: Ask documents
      operationId: ask
      parameters:
        - in: query
          name: query
          schema:
            type: string
          description: The question to ask to documents
          required: true
        - in: query
          name: collection
          schema:
            type: array
            item:
              type: string
            allowEmptyValue: true
          description: Restrict the search to these collections
      responses:
        "200":
          description: Successful operation
        "204":
          description: No result was found in documents
        "400":
          description: Request invalid or malformed
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /tasks:
    get:
      summary: List current tasks
      operationId: list-tasks
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /tasks/{taskId}:
    get:
      summary: Get task info
      operationId: get-task
      parameters:
        - in: path
          name: taskId
          schema:
            type: string
          description: The task identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The task could not be found
        "500":
          description: An unknown error occured
  /backup:
    get:
      summary: Generate a backup
      operationId: generate-backup
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The task could not be found
        "500":
          description: An unknown error occured
    put:
      summary: Restore a backup
      operationId: restore-backup
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  description: The backup to restore
                  format: binary
              required: ["file"]
      responses:
        "204":
          description: Backup restored successfully
        "400":
          description: Request invalid or malformed
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /documents:
    get:
      summary: List documents
      operationId: list-documents
      parameters:
        - in: query
          name: page
          schema:
            type: number
          description: The page offset
          min: 0
        - in: query
          name: limit
          schema:
            type: number
            min: 1
          description: Maximum number of results to return
        - in: query
          name: source
          schema:
            type: string
            allowEmptyValue: true
          description: Search for document with the given source URL
      responses:
        "200":
          description: Successful operation
        "400":
          description: Request invalid or malformed
        "403":
          description: Action forbidden to your level of authentication
        "500":
          description: An unknown error occured
  /documents/{documentId}:
    get:
      summary: Get document
      operationId: get-document
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          description: The document identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The document could not be found
        "500":
          description: An unknown error occured
  /documents/{documentId}/content:
    get:
      summary: Get document content
      operationId: get-document-content
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          description: The document identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The document could not be found
        "500":
          description: An unknown error occured
  /documents/{documentId}/reindex:
    post:
      summary: Reindex document
      operationId: reindex-document
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          description: The document identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The document could not be found
        "500":
          description: An unknown error occured
  /documents/{documentId}/sections/{sectionId}:
    get:
      summary: Get document section
      operationId: get-document-section
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          description: The document identifier
          required: true
        - in: path
          name: sectionId
          schema:
            type: string
          description: The section identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The document or section could not be found
        "500":
          description: An unknown error occured
  /documents/{documentId}/sections/{sectionId}/content:
    get:
      summary: Get section content
      operationId: get-section-content
      parameters:
        - in: path
          name: documentId
          schema:
            type: string
          description: The document identifier
          required: true
        - in: path
          name: sectionId
          schema:
            type: string
          description: The section identifier
          required: true
      responses:
        "200":
          description: Successful operation
        "403":
          description: Action forbidden to your level of authentication
        "404":
          description: The document or section could not be found
        "500":
          description: An unknown error occured
components:
  securitySchemes:
    auth:
      type: http
      scheme: basic
