// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.833
package component

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/bornholm/corpus/internal/core/model"
	common "github.com/bornholm/corpus/internal/http/handler/webui/common/component"
	"github.com/bornholm/go-x/templx/form"
)

type ProfilePageVModel struct {
	User         model.User
	AuthTokens   []model.AuthToken
	TokenForm    *form.Form
	CreatedToken string
	DeletedToken bool
	Navbar       *common.NavbarVModel
}

func ProfilePage(vmodel ProfilePageVModel) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"container\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if vmodel.Navbar != nil {
				templ_7745c5c3_Err = common.Navbar(*vmodel.Navbar).Render(ctx, templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<section class=\"section pt-3\"><div class=\"columns is-centered\"><div class=\"column is-8\"><div class=\"card\"><div class=\"card-header\"><p class=\"card-header-title\"><span class=\"icon\"><i class=\"fas fa-user\"></i></span> <span>Profil</span></p></div><div class=\"card-content\"><div class=\"content\"><div class=\"field\"><label class=\"label\">Nom d'affichage</label><div class=\"control\"><input class=\"input\" type=\"text\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(vmodel.User.DisplayName())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/handler/webui/profile/component/profile_page.templ`, Line: 41, Col: 77}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\" readonly></div></div><div class=\"field\"><label class=\"label\">Courriel</label><div class=\"control\"><input class=\"input\" type=\"text\" value=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(vmodel.User.Email())
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/handler/webui/profile/component/profile_page.templ`, Line: 47, Col: 71}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "\" readonly></div></div><div class=\"notification\"><p>Ces informations sont contrôlées par votre fournisseur d'identité et ne peuvent être modifiées.</p></div></div></div></div><!-- Auth Tokens Section --><div class=\"card mt-5\"><div class=\"card-header\"><p class=\"card-header-title\"><span class=\"icon\"><i class=\"fas fa-key\"></i></span> <span>Jetons d'authentification</span></p><div class=\"card-header-icon\"><button class=\"button is-primary is-small\" onclick=\"openTokenModal()\"><span class=\"icon\"><i class=\"fas fa-plus\"></i></span> <span>Nouveau jeton</span></button></div></div><div class=\"card-content\"><div class=\"content\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if len(vmodel.AuthTokens) == 0 {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"notification is-info is-light\"><p>Aucun jeton d'authentification configuré.</p><p>Les jetons permettent aux applications externes d'accéder à votre compte de manière sécurisée.</p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			} else {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div class=\"table-container\"><table class=\"table is-fullwidth is-striped\"><thead><tr><th>Nom</th><th>Créé le</th><th>Actions</th></tr></thead> <tbody>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				for _, token := range vmodel.AuthTokens {
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<tr><td>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var5 string
					templ_7745c5c3_Var5, templ_7745c5c3_Err = templ.JoinStringErrs(token.Label())
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/handler/webui/profile/component/profile_page.templ`, Line: 94, Col: 34}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var5))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, "</td><td>-</td><td><button class=\"button is-danger is-small\" data-token-id=\"")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					var templ_7745c5c3_Var6 string
					templ_7745c5c3_Var6, templ_7745c5c3_Err = templ.JoinStringErrs(string(token.ID()))
					if templ_7745c5c3_Err != nil {
						return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/handler/webui/profile/component/profile_page.templ`, Line: 97, Col: 92}
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var6))
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, "\" onclick=\"deleteTokenHandler(this)\"><span class=\"icon\"><i class=\"fas fa-trash\"></i></span> <span>Supprimer</span></button></td></tr>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</tbody></table></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "</div></div></div></div></div></section></div><!-- Token Creation Modal --> <div id=\"token-modal\" class=\"modal\"><div class=\"modal-background\" onclick=\"closeTokenModal()\"></div><div class=\"modal-card\"><header class=\"modal-card-head\"><p class=\"modal-card-title\">Créer un nouveau jeton</p><button class=\"delete\" aria-label=\"close\" onclick=\"closeTokenModal()\"></button></header><div class=\"modal-card-body\"><div class=\"notification is-warning is-light\"><p><strong>Important :</strong> Le jeton ne sera affiché qu'une seule fois après sa création. Assurez-vous de le copier dans un endroit sûr.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = form.FormWrapper(vmodel.TokenForm, common.BaseURL(ctx, common.WithPath("/profile/tokens")), "POST").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div><footer class=\"modal-card-foot\"><button type=\"submit\" class=\"button is-primary\" onclick=\"document.querySelector(&#39;#token-modal form&#39;).submit()\">Créer le jeton</button> <button class=\"button\" onclick=\"closeTokenModal()\">Annuler</button></footer></div></div><!-- Token Created Success Modal --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if vmodel.CreatedToken != "" {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div id=\"token-success-modal\" class=\"modal is-active\"><div class=\"modal-background\" onclick=\"closeSuccessModal()\"></div><div class=\"modal-card\"><header class=\"modal-card-head\"><p class=\"modal-card-title\">Jeton créé avec succès</p><button class=\"delete\" aria-label=\"close\" onclick=\"closeSuccessModal()\"></button></header><div class=\"modal-card-body\"><div class=\"notification is-success\"><p><strong>Votre nouveau jeton d'authentification :</strong></p><div class=\"field has-addons\"><div class=\"control is-expanded\"><input class=\"input\" type=\"text\" value=\"")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				var templ_7745c5c3_Var7 string
				templ_7745c5c3_Var7, templ_7745c5c3_Err = templ.JoinStringErrs(vmodel.CreatedToken)
				if templ_7745c5c3_Err != nil {
					return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/http/handler/webui/profile/component/profile_page.templ`, Line: 151, Col: 69}
				}
				_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var7))
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "\" readonly id=\"created-token\"></div><div class=\"control\"><button class=\"button is-info\" onclick=\"copyToken()\"><span class=\"icon\"><i class=\"fas fa-copy\"></i></span> <span>Copier</span></button></div></div><p class=\"help is-danger\"><strong>Attention :</strong> Ce jeton ne sera plus affiché. Copiez-le maintenant dans un endroit sûr.</p></div></div><footer class=\"modal-card-foot\"><button class=\"button is-primary\" onclick=\"closeSuccessModal()\">J'ai copié le jeton</button></footer></div></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, " <!-- Token Deleted Success Notification --> ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			if vmodel.DeletedToken {
				templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, "<div class=\"notification is-success is-light\" style=\"position: fixed; top: 20px; right: 20px; z-index: 1000;\"><button class=\"delete\" onclick=\"this.parentElement.style.display=&#39;none&#39;\"></button><p><strong>Jeton supprimé avec succès</strong></p></div>")
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " <script>\n\t\t\tfunction openTokenModal() {\n\t\t\t\tdocument.getElementById('token-modal').classList.add('is-active');\n\t\t\t}\n\t\t\t\n\t\t\tfunction closeTokenModal() {\n\t\t\t\tdocument.getElementById('token-modal').classList.remove('is-active');\n\t\t\t}\n\t\t\t\n\t\t\tfunction closeSuccessModal() {\n\t\t\t\tdocument.getElementById('token-success-modal').classList.remove('is-active');\n\t\t\t}\n\t\t\t\n\t\t\tfunction copyToken() {\n\t\t\t\tconst tokenInput = document.getElementById('created-token');\n\t\t\t\ttokenInput.select();\n\t\t\t\tdocument.execCommand('copy');\n\t\t\t\t\n\t\t\t\tconst button = event.target.closest('button');\n\t\t\t\tconst originalText = button.innerHTML;\n\t\t\t\tbutton.innerHTML = '<span class=\"icon\"><i class=\"fas fa-check\"></i></span><span>Copié!</span>';\n\t\t\t\tbutton.classList.remove('is-info');\n\t\t\t\tbutton.classList.add('is-success');\n\t\t\t\t\n\t\t\t\tsetTimeout(() => {\n\t\t\t\t\tbutton.innerHTML = originalText;\n\t\t\t\t\tbutton.classList.remove('is-success');\n\t\t\t\t\tbutton.classList.add('is-info');\n\t\t\t\t}, 2000);\n\t\t\t}\n\t\t\t\n\t\t\tfunction deleteTokenHandler(button) {\n\t\t\t\tconst tokenId = button.getAttribute('data-token-id');\n\t\t\t\tif (confirm('Êtes-vous sûr de vouloir supprimer ce jeton ? Cette action est irréversible.')) {\n\t\t\t\t\tfetch('/profile/tokens/' + tokenId, {\n\t\t\t\t\t\tmethod: 'DELETE',\n\t\t\t\t\t}).then(() => {\n\t\t\t\t\t\twindow.location.reload();\n\t\t\t\t\t});\n\t\t\t\t}\n\t\t\t}\n\t\t</script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = common.Page(common.WithTitle("Profil")).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
